[buttons]
backward = 'Backward'
forward = 'Forward'
left = 'Left-Click'
middle = 'Middle-Click'
right = 'Right-Click'

[device]
name = 'Darmoshark M3'
pid = 0xFF12
vid = 0x248A

[dpi]
current_stage = 4
stages = [ 400, 800, 1600, 3200, 4800 ]

[ui]
angle_snap_enabled = false
esports_open = false
lift_off_high = false
motion_sync_enabled = true
polling_rate = 1000
ripple_enabled = false
scroll_normal = true